# Generated by Django 5.2.3 on 2025-07-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcam_app', '0003_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
